services:

  mqtt:
    image: emqx:latest
    ports:
    - "1883:1883"
    - "18083:18083"

  view:
    build:
    context: ./view
    ports:
    - "3000:80" # map 80 in container => 3000 in local
  serving:
    build: ./serving
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]